#!/bin/bash
is_running=$(ps -ef | grep "/root/evebox server -v -D /root --datastore sqlite --input /var/log/suricata/eve.json --host 0.0.0.0" | grep -v "grep")
if [[ $is_running != "" ]]
then
        echo "Evebox is running!"
else
        date=$(date)
        echo "Evebox is not running - Starting it......$date" >> /root/Pi-IDS.log
        /root/evebox server -v -D /root --datastore sqlite --input /var/log/suricata/eve.json --host 0.0.0.0
fi
